[build]
  publish = "public"
  command = "hugo --minify"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.128.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
